### ISSUE TITLE
python traceback

### ISSUE THREAD

**Issue by Ayanashi** [deep5050/radio-active#117]
```
Traceback (most recent call last):
  File "/usr/bin/radio", line 5, in <module>
    from radioactive.__main__ import main
  File "/usr/lib/python3.12/site-packages/radioactive/__main__.py", line 12, in <module>
    from radioactive.handler import Handler
  File "/usr/lib/python3.12/site-packages/radioactive/handler.py", line 9, in <module>
    import requests_cache
  File "/usr/lib/python3.12/site-packages/requests_cache/__init__.py", line 7, in <module>
    from .backends import *
  File "/usr/lib/python3.12/site-packages/requests_cache/backends/__init__.py", line 8, in <module>
    from .base import BaseCache, BaseStorage, DictStorage
  File "/usr/lib/python3.12/site-packages/requests_cache/backends/base.py", line 27, in <module>
    from ..cache_keys import create_key, redact_response
  File "/usr/lib/python3.12/site-packages/requests_cache/cache_keys.py", line 29, in <module>
    from url_normalize import url_normalize
ModuleNotFoundError: No module named 'url_normalize'
```
Archlinux 6.9.4-zen
python 3.12
radioactive-2.9.1-2 (from aur)

**Comment by Ayanashi** [comment]
Solved installing missing python modules
