### ISSUE TITLE
ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by robinhood2014** [deep5050/radio-active#119]
**Describe the bug**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\donni\.local\bin\radioactive.exe\__main__.py", line 4, in <module>
    from radioactive.__main__ import main
  File "C:\Users\donni\pipx\venvs\radio-active\Lib\site-packages\radioactive\__main__.py", line 9, in <module>
    from radioactive.alias import Alias
  File "C:\Users\donni\pipx\venvs\radio-active\Lib\site-packages\radioactive\alias.py", line 3, in <module>
    from pick import pick
  File "C:\Users\donni\pipx\venvs\radio-active\Lib\site-packages\pick\__init__.py", line 3, in <module>
    import curses
  File "C:\Users\donni\AppData\Local\Programs\Python\Python313\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**To Reproduce**
1. Install Python
2. Open terminal
3. Type `pip install pipx setuptools` (dependencies for radio-active)
4. Type `pipx install radio-active`
5. Optionally, type `pipx ensurepath` followed by `pipx completions`
6. Close and reopen terminal
7. Type `radio`
8. See error

**Expected behavior**
I expected an about box to appear, followed by a message saying `No stations to play. please search for a station first!`

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 133.0

**Comment by robinhood2014** [comment]
Update: Issue is not reproducible in Linux; it only occurs in Windows, and may also occur in macOS; however, I do not have a Mac on which to test.
