### ISSUE TITLE
module 'signal' has no attribute 'pause'

### ISSUE THREAD

**Issue by arpitkaushal** [deep5050/radio-active#14]
**Describe the bug**
The first command I issued `radioactive --station pehla_nasha` causes the following output.

```
G:\Desktop>radioactive --station pehla_nasha
     [!]    | Alias file does not exist
┌─────────────────────────────────── RADIOACTIVE ───────────────────────────────────┐
│                                                                                   │
│         📻 Play any radios around the globe right from this Terminal ⚡!          │
│         😄 Author: Dipankar Pal                                                   │
│         ❓ Type '--help' for more details on avaliable commands.                  │
│         🐛 Visit https://github.com/deep5050/radio-active to submit issues        │
│         ⭐ Show some love by starring the project on GitHub ❤                     │
│         ❌ Press Ctrl+C to quit                                                   │
│                                                                                   │
└───────────────────────────────────────────────────────────────────────────────────┘
      i     | Station found: Radio Mirchi - Pehla Nasha
      i     | Radio started successfully
┌─────────────────────────────────────── 📻 ────────────────────────────────────────┐
│                           Radio Mirchi - Pehla Nasha/n                            │
└───────────────────────────────────────────────────────────────────────────────────┘
Traceback (most recent call last):
  File "c:\users\arpit\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\arpit\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\arpit\AppData\Local\Programs\Python\Python39\Scripts\radioactive.exe\__main__.py", line 7, in <module>
  File "c:\users\arpit\appdata\local\programs\python\python39\lib\site-packages\radioactive\__main__.py", line 311, in main
    signal.pause()
AttributeError: module 'signal' has no attribute 'pause'

```

**Desktop (please complete the following information):**
 - Windows 10
 - Command Prompt

**Comment by deep5050** [comment]
Thanks for the report. Working on it now.

**Comment by deep5050** [comment]
pip install radio-active==2.4.0

would you take a look and get back to me?
